import { useEffect, useState } from "react";
import { fetchControlTotals, fetchRawRows, fetchRejections, type ControlTotal, type IngestionSummary, type RawRow, type Rejection } from "../api/ingestion";

export function IngestionView({ ingestion, onClose }: { ingestion: IngestionSummary; onClose: () => void }) {
  const [raw, setRaw] = useState<RawRow[]>([]); const [rejections, setRejections] = useState<Rejection[]>([]);
  const [controls, setControls] = useState<ControlTotal[]>([]); const [category, setCategory] = useState("");
  useEffect(() => { void Promise.all([fetchRawRows(ingestion.id), fetchRejections(ingestion.id), fetchControlTotals(ingestion.id)]).then(([rows, rejected, totals]) => { setRaw(rows); setRejections(rejected); setControls(totals); }); }, [ingestion.id]);
  const shown = rejections.filter((item) => !category || item.rejection_category === category);
  const pct = ingestion.records_extracted ? (100 * ingestion.records_accepted / ingestion.records_extracted).toFixed(1) : "0.0";
  return <section><button className="close-button" onClick={onClose}>Back to source files</button><p className="eyebrow">Phase 4 · Raw and staging ingestion</p><h2>{ingestion.source_filename}</h2>
    {ingestion.no_op && <p className="upload-message duplicate">Safe no-op: this mapping and ingestion version were already completed.</p>}
    <div className="metric-grid"><article><span>Status</span><strong>{ingestion.status}</strong></article><article><span>Connector</span><strong>{ingestion.connector ?? "—"}</strong></article><article><span>Mapping</span><strong>{ingestion.mapping_code} v{ingestion.mapping_version}</strong></article><article><span>Ingestion</span><strong>v{ingestion.ingestion_version}</strong></article><article><span>Extracted</span><strong>{ingestion.records_extracted}</strong></article><article><span>Accepted</span><strong>{ingestion.records_accepted} ({pct}%)</strong></article><article><span>Rejected</span><strong>{ingestion.records_rejected}</strong></article></div>
    <h3>Control totals</h3><div className="table-wrap"><table><thead><tr><th>Control</th><th>Source</th><th>Loaded</th><th>Difference</th><th>Status</th></tr></thead><tbody>{controls.map((item) => <tr key={item.id}><td>{item.control_name}</td><td>{item.source_value ?? "—"}</td><td>{item.loaded_value ?? "—"}</td><td>{item.difference_value ?? "—"}</td><td>{item.status}</td></tr>)}</tbody></table></div>
    <h3>Rejected rows</h3><label>Category <select value={category} onChange={(event) => setCategory(event.target.value)}><option value="">All</option>{[...new Set(rejections.map((item) => item.rejection_category))].map((value) => <option key={value}>{value}</option>)}</select></label><div className="table-wrap"><table><thead><tr><th>Row</th><th>Code</th><th>Category</th><th>Field</th><th>Observed</th><th>Message</th><th>Severity</th></tr></thead><tbody>{shown.map((item) => <tr key={item.id}><td>{item.source_row_number}</td><td>{item.rejection_code}</td><td>{item.rejection_category}</td><td>{item.field_name ?? "—"}</td><td>{item.observed_value?.slice(0, 80) ?? "—"}</td><td>{item.message}</td><td>{item.severity}</td></tr>)}</tbody></table></div>
    <h3>Raw rows</h3><div className="table-wrap"><table><thead><tr><th>Row</th><th>Record ID</th><th>Status</th><th>Hash</th><th>Created</th><th>Preview</th></tr></thead><tbody>{raw.map((item) => <tr key={item.id}><td>{item.source_row_number}</td><td>{item.source_record_id ?? "—"}</td><td>{item.row_status}</td><td><code>{item.raw_row_hash.slice(0, 12)}…</code></td><td>{new Date(item.created_at).toLocaleString()}</td><td><details><summary>Open</summary><code>{JSON.stringify(item.raw_data_json).slice(0, 500)}</code></details></td></tr>)}</tbody></table></div>
    <h3>Pipeline steps</h3><ol>{ingestion.steps.map((step) => <li key={step.step_order}><strong>{step.step_name}</strong> · {step.status}</li>)}</ol><h3>Artifacts</h3><ul>{ingestion.artifacts.map((item) => <li key={item.id}>{item.artifact_type}: <code>{item.relative_path}</code></li>)}</ul>
  </section>;
}
