"""add raw and staging ingestion

Revision ID: 496fc87bdd17
Revises: 20260714_0004
Create Date: 2026-07-14 14:10:20.699310
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '496fc87bdd17'
down_revision: str | None = '20260714_0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('source_schema_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=True),
    sa.Column('source_file_pattern', sa.String(length=255), nullable=False),
    sa.Column('mapping_code', sa.String(length=100), nullable=False),
    sa.Column('mapping_name', sa.String(length=255), nullable=False),
    sa.Column('mapping_version', sa.String(length=30), nullable=False),
    sa.Column('target_record_type', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('required_columns_json', sa.JSON(), nullable=False),
    sa.Column('optional_columns_json', sa.JSON(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'mapping_code', 'mapping_version', name='uq_schema_mapping_version')
    )
    op.create_index(op.f('ix_source_schema_mappings_is_active'), 'source_schema_mappings', ['is_active'], unique=False)
    op.create_index(op.f('ix_source_schema_mappings_mapping_code'), 'source_schema_mappings', ['mapping_code'], unique=False)
    op.create_index(op.f('ix_source_schema_mappings_source_system_id'), 'source_schema_mappings', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_source_schema_mappings_target_record_type'), 'source_schema_mappings', ['target_record_type'], unique=False)
    op.create_index(op.f('ix_source_schema_mappings_tenant_id'), 'source_schema_mappings', ['tenant_id'], unique=False)
    op.create_table('source_schema_mapping_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_schema_mapping_id', sa.Integer(), nullable=False),
    sa.Column('source_column_name', sa.String(length=255), nullable=False),
    sa.Column('canonical_field_name', sa.String(length=100), nullable=False),
    sa.Column('target_data_type', sa.String(length=30), nullable=False),
    sa.Column('is_required', sa.Boolean(), nullable=False),
    sa.Column('parser_name', sa.String(length=100), nullable=True),
    sa.Column('default_value_json', sa.JSON(), nullable=True),
    sa.Column('transformation_config_json', sa.JSON(), nullable=True),
    sa.Column('column_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['source_schema_mapping_id'], ['source_schema_mappings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_schema_mapping_id', 'canonical_field_name', name='uq_mapping_canonical_field')
    )
    op.create_index(op.f('ix_source_schema_mapping_columns_source_schema_mapping_id'), 'source_schema_mapping_columns', ['source_schema_mapping_id'], unique=False)
    op.create_table('ingestion_control_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('control_name', sa.String(length=100), nullable=False),
    sa.Column('source_value', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('loaded_value', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('difference_value', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('tolerance', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_run_id', 'control_name', name='uq_run_control_total')
    )
    op.create_index(op.f('ix_ingestion_control_totals_control_name'), 'ingestion_control_totals', ['control_name'], unique=False)
    op.create_index(op.f('ix_ingestion_control_totals_pipeline_run_id'), 'ingestion_control_totals', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_ingestion_control_totals_source_file_id'), 'ingestion_control_totals', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_ingestion_control_totals_status'), 'ingestion_control_totals', ['status'], unique=False)
    op.create_index(op.f('ix_ingestion_control_totals_tenant_id'), 'ingestion_control_totals', ['tenant_id'], unique=False)
    op.create_table('raw_source_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('raw_data_json', sa.JSON(), nullable=False),
    sa.Column('raw_row_hash', sa.String(length=64), nullable=False),
    sa.Column('ingestion_version', sa.String(length=30), nullable=False),
    sa.Column('row_status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_file_id', 'source_row_number', 'ingestion_version', name='uq_raw_row_ingestion')
    )
    op.create_index(op.f('ix_raw_source_rows_pipeline_run_id'), 'raw_source_rows', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_raw_source_rows_raw_row_hash'), 'raw_source_rows', ['raw_row_hash'], unique=False)
    op.create_index(op.f('ix_raw_source_rows_row_status'), 'raw_source_rows', ['row_status'], unique=False)
    op.create_index(op.f('ix_raw_source_rows_source_file_id'), 'raw_source_rows', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_raw_source_rows_source_record_id'), 'raw_source_rows', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_raw_source_rows_source_system_id'), 'raw_source_rows', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_raw_source_rows_tenant_id'), 'raw_source_rows', ['tenant_id'], unique=False)
    op.create_table('rejected_source_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('raw_source_row_id', sa.Integer(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('rejection_code', sa.String(length=100), nullable=False),
    sa.Column('rejection_category', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('field_name', sa.String(length=255), nullable=True),
    sa.Column('observed_value', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('rejection_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_source_row_id'], ['raw_source_rows.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'raw_source_row_id', 'rejection_fingerprint', name='uq_raw_row_rejection')
    )
    op.create_index(op.f('ix_rejected_source_rows_pipeline_run_id'), 'rejected_source_rows', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_rejected_source_rows_raw_source_row_id'), 'rejected_source_rows', ['raw_source_row_id'], unique=False)
    op.create_index(op.f('ix_rejected_source_rows_rejection_category'), 'rejected_source_rows', ['rejection_category'], unique=False)
    op.create_index(op.f('ix_rejected_source_rows_rejection_code'), 'rejected_source_rows', ['rejection_code'], unique=False)
    op.create_index(op.f('ix_rejected_source_rows_severity'), 'rejected_source_rows', ['severity'], unique=False)
    op.create_index(op.f('ix_rejected_source_rows_source_file_id'), 'rejected_source_rows', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_rejected_source_rows_source_system_id'), 'rejected_source_rows', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_rejected_source_rows_tenant_id'), 'rejected_source_rows', ['tenant_id'], unique=False)
    op.create_table('staging_bank_transactions',
    sa.Column('account_source_code', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('running_balance', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('counterparty_raw', sa.Text(), nullable=True),
    sa.Column('category_raw', sa.Text(), nullable=True),
    sa.Column('memo_raw', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('raw_source_row_id', sa.Integer(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('ingestion_version', sa.String(length=30), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_source_row_id'], ['raw_source_rows.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_file_id', 'source_row_number', 'ingestion_version', name='uq_staging_bank_row')
    )
    op.create_index(op.f('ix_staging_bank_transactions_account_source_code'), 'staging_bank_transactions', ['account_source_code'], unique=False)
    op.create_index(op.f('ix_staging_bank_transactions_pipeline_run_id'), 'staging_bank_transactions', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_staging_bank_transactions_raw_source_row_id'), 'staging_bank_transactions', ['raw_source_row_id'], unique=False)
    op.create_index(op.f('ix_staging_bank_transactions_row_hash'), 'staging_bank_transactions', ['row_hash'], unique=False)
    op.create_index(op.f('ix_staging_bank_transactions_source_file_id'), 'staging_bank_transactions', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_staging_bank_transactions_source_record_id'), 'staging_bank_transactions', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_staging_bank_transactions_source_system_id'), 'staging_bank_transactions', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_staging_bank_transactions_tenant_id'), 'staging_bank_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_staging_bank_transactions_transaction_date'), 'staging_bank_transactions', ['transaction_date'], unique=False)
    op.create_table('staging_credit_card_transactions',
    sa.Column('credit_account_source_code', sa.String(length=255), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('merchant_raw', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('debit_amount', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('category_raw', sa.Text(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('memo_raw', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('raw_source_row_id', sa.Integer(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('ingestion_version', sa.String(length=30), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_source_row_id'], ['raw_source_rows.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_file_id', 'source_row_number', 'ingestion_version', name='uq_staging_card_row')
    )
    op.create_index(op.f('ix_staging_credit_card_transactions_credit_account_source_code'), 'staging_credit_card_transactions', ['credit_account_source_code'], unique=False)
    op.create_index(op.f('ix_staging_credit_card_transactions_pipeline_run_id'), 'staging_credit_card_transactions', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_staging_credit_card_transactions_raw_source_row_id'), 'staging_credit_card_transactions', ['raw_source_row_id'], unique=False)
    op.create_index(op.f('ix_staging_credit_card_transactions_row_hash'), 'staging_credit_card_transactions', ['row_hash'], unique=False)
    op.create_index(op.f('ix_staging_credit_card_transactions_source_file_id'), 'staging_credit_card_transactions', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_staging_credit_card_transactions_source_record_id'), 'staging_credit_card_transactions', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_staging_credit_card_transactions_source_system_id'), 'staging_credit_card_transactions', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_staging_credit_card_transactions_tenant_id'), 'staging_credit_card_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_staging_credit_card_transactions_transaction_date'), 'staging_credit_card_transactions', ['transaction_date'], unique=False)
    op.create_table('staging_payroll_details',
    sa.Column('payroll_run_source_id', sa.String(length=255), nullable=True),
    sa.Column('pay_period_start', sa.Date(), nullable=True),
    sa.Column('pay_period_end', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('employee_source_id', sa.String(length=255), nullable=False),
    sa.Column('employee_name_raw', sa.Text(), nullable=True),
    sa.Column('earning_type_raw', sa.Text(), nullable=True),
    sa.Column('deduction_type_raw', sa.Text(), nullable=True),
    sa.Column('gross_pay', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('regular_pay', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('overtime_pay', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('bonus_pay', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('reimbursement_amount', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('employee_tax', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('employee_deduction', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('employer_tax', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('employer_contribution', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('net_pay', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('raw_source_row_id', sa.Integer(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('ingestion_version', sa.String(length=30), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_source_row_id'], ['raw_source_rows.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_file_id', 'source_row_number', 'ingestion_version', name='uq_staging_payroll_detail_row')
    )
    op.create_index(op.f('ix_staging_payroll_details_employee_source_id'), 'staging_payroll_details', ['employee_source_id'], unique=False)
    op.create_index(op.f('ix_staging_payroll_details_pay_date'), 'staging_payroll_details', ['pay_date'], unique=False)
    op.create_index(op.f('ix_staging_payroll_details_pipeline_run_id'), 'staging_payroll_details', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_staging_payroll_details_raw_source_row_id'), 'staging_payroll_details', ['raw_source_row_id'], unique=False)
    op.create_index(op.f('ix_staging_payroll_details_row_hash'), 'staging_payroll_details', ['row_hash'], unique=False)
    op.create_index(op.f('ix_staging_payroll_details_source_file_id'), 'staging_payroll_details', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_staging_payroll_details_source_record_id'), 'staging_payroll_details', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_staging_payroll_details_source_system_id'), 'staging_payroll_details', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_staging_payroll_details_tenant_id'), 'staging_payroll_details', ['tenant_id'], unique=False)
    op.create_table('staging_payroll_summaries',
    sa.Column('payroll_run_source_id', sa.String(length=255), nullable=True),
    sa.Column('pay_period_start', sa.Date(), nullable=True),
    sa.Column('pay_period_end', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('employee_source_id', sa.String(length=255), nullable=False),
    sa.Column('employee_name_raw', sa.Text(), nullable=True),
    sa.Column('gross_pay', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('employee_deductions', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('employer_contributions', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('reimbursements', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('net_pay', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('raw_source_row_id', sa.Integer(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('ingestion_version', sa.String(length=30), nullable=False),
    sa.Column('row_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_source_row_id'], ['raw_source_rows.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_file_id', 'source_row_number', 'ingestion_version', name='uq_staging_payroll_summary_row')
    )
    op.create_index(op.f('ix_staging_payroll_summaries_employee_source_id'), 'staging_payroll_summaries', ['employee_source_id'], unique=False)
    op.create_index(op.f('ix_staging_payroll_summaries_pay_date'), 'staging_payroll_summaries', ['pay_date'], unique=False)
    op.create_index(op.f('ix_staging_payroll_summaries_pipeline_run_id'), 'staging_payroll_summaries', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_staging_payroll_summaries_raw_source_row_id'), 'staging_payroll_summaries', ['raw_source_row_id'], unique=False)
    op.create_index(op.f('ix_staging_payroll_summaries_row_hash'), 'staging_payroll_summaries', ['row_hash'], unique=False)
    op.create_index(op.f('ix_staging_payroll_summaries_source_file_id'), 'staging_payroll_summaries', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_staging_payroll_summaries_source_record_id'), 'staging_payroll_summaries', ['source_record_id'], unique=False)
    op.create_index(op.f('ix_staging_payroll_summaries_source_system_id'), 'staging_payroll_summaries', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_staging_payroll_summaries_tenant_id'), 'staging_payroll_summaries', ['tenant_id'], unique=False)
    op.add_column('pipeline_runs', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.execute(
        """
        INSERT INTO permissions (code, name)
        VALUES
          ('source_files.ingest', 'Source Files Ingest'),
          ('raw_rows.view', 'Raw Rows View'),
          ('rejected_rows.view', 'Rejected Rows View'),
          ('staging_records.view', 'Staging Records View'),
          ('ingestion_control_totals.view', 'Ingestion Control Totals View')
        ON CONFLICT (code) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id
        FROM roles r CROSS JOIN permissions p
        WHERE r.code IN ('platform_admin', 'cfo_user', 'finance_analyst')
          AND p.code IN (
            'source_files.ingest', 'raw_rows.view', 'rejected_rows.view',
            'staging_records.view', 'ingestion_control_totals.view'
          )
        ON CONFLICT (role_id, permission_id) DO NOTHING
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM role_permissions
        WHERE permission_id IN (
          SELECT id FROM permissions WHERE code IN (
            'source_files.ingest', 'raw_rows.view', 'rejected_rows.view',
            'staging_records.view', 'ingestion_control_totals.view'
          )
        )
        """
    )
    op.execute(
        """
        DELETE FROM permissions WHERE code IN (
          'source_files.ingest', 'raw_rows.view', 'rejected_rows.view',
          'staging_records.view', 'ingestion_control_totals.view'
        )
        """
    )
    op.drop_column('pipeline_runs', 'metadata_json')
    op.drop_index(op.f('ix_staging_payroll_summaries_tenant_id'), table_name='staging_payroll_summaries')
    op.drop_index(op.f('ix_staging_payroll_summaries_source_system_id'), table_name='staging_payroll_summaries')
    op.drop_index(op.f('ix_staging_payroll_summaries_source_record_id'), table_name='staging_payroll_summaries')
    op.drop_index(op.f('ix_staging_payroll_summaries_source_file_id'), table_name='staging_payroll_summaries')
    op.drop_index(op.f('ix_staging_payroll_summaries_row_hash'), table_name='staging_payroll_summaries')
    op.drop_index(op.f('ix_staging_payroll_summaries_raw_source_row_id'), table_name='staging_payroll_summaries')
    op.drop_index(op.f('ix_staging_payroll_summaries_pipeline_run_id'), table_name='staging_payroll_summaries')
    op.drop_index(op.f('ix_staging_payroll_summaries_pay_date'), table_name='staging_payroll_summaries')
    op.drop_index(op.f('ix_staging_payroll_summaries_employee_source_id'), table_name='staging_payroll_summaries')
    op.drop_table('staging_payroll_summaries')
    op.drop_index(op.f('ix_staging_payroll_details_tenant_id'), table_name='staging_payroll_details')
    op.drop_index(op.f('ix_staging_payroll_details_source_system_id'), table_name='staging_payroll_details')
    op.drop_index(op.f('ix_staging_payroll_details_source_record_id'), table_name='staging_payroll_details')
    op.drop_index(op.f('ix_staging_payroll_details_source_file_id'), table_name='staging_payroll_details')
    op.drop_index(op.f('ix_staging_payroll_details_row_hash'), table_name='staging_payroll_details')
    op.drop_index(op.f('ix_staging_payroll_details_raw_source_row_id'), table_name='staging_payroll_details')
    op.drop_index(op.f('ix_staging_payroll_details_pipeline_run_id'), table_name='staging_payroll_details')
    op.drop_index(op.f('ix_staging_payroll_details_pay_date'), table_name='staging_payroll_details')
    op.drop_index(op.f('ix_staging_payroll_details_employee_source_id'), table_name='staging_payroll_details')
    op.drop_table('staging_payroll_details')
    op.drop_index(op.f('ix_staging_credit_card_transactions_transaction_date'), table_name='staging_credit_card_transactions')
    op.drop_index(op.f('ix_staging_credit_card_transactions_tenant_id'), table_name='staging_credit_card_transactions')
    op.drop_index(op.f('ix_staging_credit_card_transactions_source_system_id'), table_name='staging_credit_card_transactions')
    op.drop_index(op.f('ix_staging_credit_card_transactions_source_record_id'), table_name='staging_credit_card_transactions')
    op.drop_index(op.f('ix_staging_credit_card_transactions_source_file_id'), table_name='staging_credit_card_transactions')
    op.drop_index(op.f('ix_staging_credit_card_transactions_row_hash'), table_name='staging_credit_card_transactions')
    op.drop_index(op.f('ix_staging_credit_card_transactions_raw_source_row_id'), table_name='staging_credit_card_transactions')
    op.drop_index(op.f('ix_staging_credit_card_transactions_pipeline_run_id'), table_name='staging_credit_card_transactions')
    op.drop_index(op.f('ix_staging_credit_card_transactions_credit_account_source_code'), table_name='staging_credit_card_transactions')
    op.drop_table('staging_credit_card_transactions')
    op.drop_index(op.f('ix_staging_bank_transactions_transaction_date'), table_name='staging_bank_transactions')
    op.drop_index(op.f('ix_staging_bank_transactions_tenant_id'), table_name='staging_bank_transactions')
    op.drop_index(op.f('ix_staging_bank_transactions_source_system_id'), table_name='staging_bank_transactions')
    op.drop_index(op.f('ix_staging_bank_transactions_source_record_id'), table_name='staging_bank_transactions')
    op.drop_index(op.f('ix_staging_bank_transactions_source_file_id'), table_name='staging_bank_transactions')
    op.drop_index(op.f('ix_staging_bank_transactions_row_hash'), table_name='staging_bank_transactions')
    op.drop_index(op.f('ix_staging_bank_transactions_raw_source_row_id'), table_name='staging_bank_transactions')
    op.drop_index(op.f('ix_staging_bank_transactions_pipeline_run_id'), table_name='staging_bank_transactions')
    op.drop_index(op.f('ix_staging_bank_transactions_account_source_code'), table_name='staging_bank_transactions')
    op.drop_table('staging_bank_transactions')
    op.drop_index(op.f('ix_rejected_source_rows_tenant_id'), table_name='rejected_source_rows')
    op.drop_index(op.f('ix_rejected_source_rows_source_system_id'), table_name='rejected_source_rows')
    op.drop_index(op.f('ix_rejected_source_rows_source_file_id'), table_name='rejected_source_rows')
    op.drop_index(op.f('ix_rejected_source_rows_severity'), table_name='rejected_source_rows')
    op.drop_index(op.f('ix_rejected_source_rows_rejection_code'), table_name='rejected_source_rows')
    op.drop_index(op.f('ix_rejected_source_rows_rejection_category'), table_name='rejected_source_rows')
    op.drop_index(op.f('ix_rejected_source_rows_raw_source_row_id'), table_name='rejected_source_rows')
    op.drop_index(op.f('ix_rejected_source_rows_pipeline_run_id'), table_name='rejected_source_rows')
    op.drop_table('rejected_source_rows')
    op.drop_index(op.f('ix_raw_source_rows_tenant_id'), table_name='raw_source_rows')
    op.drop_index(op.f('ix_raw_source_rows_source_system_id'), table_name='raw_source_rows')
    op.drop_index(op.f('ix_raw_source_rows_source_record_id'), table_name='raw_source_rows')
    op.drop_index(op.f('ix_raw_source_rows_source_file_id'), table_name='raw_source_rows')
    op.drop_index(op.f('ix_raw_source_rows_row_status'), table_name='raw_source_rows')
    op.drop_index(op.f('ix_raw_source_rows_raw_row_hash'), table_name='raw_source_rows')
    op.drop_index(op.f('ix_raw_source_rows_pipeline_run_id'), table_name='raw_source_rows')
    op.drop_table('raw_source_rows')
    op.drop_index(op.f('ix_ingestion_control_totals_tenant_id'), table_name='ingestion_control_totals')
    op.drop_index(op.f('ix_ingestion_control_totals_status'), table_name='ingestion_control_totals')
    op.drop_index(op.f('ix_ingestion_control_totals_source_file_id'), table_name='ingestion_control_totals')
    op.drop_index(op.f('ix_ingestion_control_totals_pipeline_run_id'), table_name='ingestion_control_totals')
    op.drop_index(op.f('ix_ingestion_control_totals_control_name'), table_name='ingestion_control_totals')
    op.drop_table('ingestion_control_totals')
    op.drop_index(op.f('ix_source_schema_mapping_columns_source_schema_mapping_id'), table_name='source_schema_mapping_columns')
    op.drop_table('source_schema_mapping_columns')
    op.drop_index(op.f('ix_source_schema_mappings_tenant_id'), table_name='source_schema_mappings')
    op.drop_index(op.f('ix_source_schema_mappings_target_record_type'), table_name='source_schema_mappings')
    op.drop_index(op.f('ix_source_schema_mappings_source_system_id'), table_name='source_schema_mappings')
    op.drop_index(op.f('ix_source_schema_mappings_mapping_code'), table_name='source_schema_mappings')
    op.drop_index(op.f('ix_source_schema_mappings_is_active'), table_name='source_schema_mappings')
    op.drop_table('source_schema_mappings')
    # ### end Alembic commands ###
