"""add controlled messy data

Revision ID: 8276076097a8
Revises: 9f4b7143843e
Create Date: 2026-07-14 16:03:09.905367
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '8276076097a8'
down_revision: str | None = '9f4b7143843e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('defect_scenarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('is_system_scenario', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', 'version', name='uq_defect_scenario_version')
    )
    op.create_index(op.f('ix_defect_scenarios_code'), 'defect_scenarios', ['code'], unique=False)
    op.create_index(op.f('ix_defect_scenarios_is_active'), 'defect_scenarios', ['is_active'], unique=False)
    op.create_index(op.f('ix_defect_scenarios_tenant_id'), 'defect_scenarios', ['tenant_id'], unique=False)
    op.create_table('defect_scenario_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_scenario_id', sa.Integer(), nullable=False),
    sa.Column('rule_code', sa.String(length=120), nullable=False),
    sa.Column('defect_type', sa.String(length=100), nullable=False),
    sa.Column('target_file_type', sa.String(length=100), nullable=False),
    sa.Column('target_column', sa.String(length=120), nullable=True),
    sa.Column('requested_count', sa.Integer(), nullable=True),
    sa.Column('requested_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('rule_order', sa.Integer(), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['defect_scenario_id'], ['defect_scenarios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('defect_scenario_id', 'rule_code', name='uq_defect_scenario_rule'),
    sa.UniqueConstraint('defect_scenario_id', 'rule_order', name='uq_defect_scenario_rule_order')
    )
    op.create_index(op.f('ix_defect_scenario_rules_defect_scenario_id'), 'defect_scenario_rules', ['defect_scenario_id'], unique=False)
    op.create_index(op.f('ix_defect_scenario_rules_defect_type'), 'defect_scenario_rules', ['defect_type'], unique=False)
    op.create_index(op.f('ix_defect_scenario_rules_is_enabled'), 'defect_scenario_rules', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_defect_scenario_rules_rule_code'), 'defect_scenario_rules', ['rule_code'], unique=False)
    op.create_index(op.f('ix_defect_scenario_rules_severity'), 'defect_scenario_rules', ['severity'], unique=False)
    op.create_index(op.f('ix_defect_scenario_rules_target_file_type'), 'defect_scenario_rules', ['target_file_type'], unique=False)
    op.create_table('messy_dataset_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('clean_generated_dataset_run_id', sa.Integer(), nullable=False),
    sa.Column('defect_scenario_id', sa.Integer(), nullable=False),
    sa.Column('messy_generator_version', sa.String(length=30), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('defect_plan_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('output_fingerprint', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clean_file_count', sa.Integer(), nullable=False),
    sa.Column('messy_file_count', sa.Integer(), nullable=False),
    sa.Column('requested_defect_count', sa.Integer(), nullable=False),
    sa.Column('applied_defect_count', sa.Integer(), nullable=False),
    sa.Column('skipped_defect_count', sa.Integer(), nullable=False),
    sa.Column('failed_defect_count', sa.Integer(), nullable=False),
    sa.Column('expected_exception_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clean_generated_dataset_run_id'], ['generated_dataset_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['defect_scenario_id'], ['defect_scenarios.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_run_id'),
    sa.UniqueConstraint('tenant_id', 'clean_generated_dataset_run_id', 'defect_scenario_id', 'random_seed', 'input_fingerprint', 'defect_plan_fingerprint', name='uq_messy_dataset_inputs')
    )
    op.create_index(op.f('ix_messy_dataset_runs_clean_generated_dataset_run_id'), 'messy_dataset_runs', ['clean_generated_dataset_run_id'], unique=False)
    op.create_index(op.f('ix_messy_dataset_runs_defect_plan_fingerprint'), 'messy_dataset_runs', ['defect_plan_fingerprint'], unique=False)
    op.create_index(op.f('ix_messy_dataset_runs_defect_scenario_id'), 'messy_dataset_runs', ['defect_scenario_id'], unique=False)
    op.create_index(op.f('ix_messy_dataset_runs_input_fingerprint'), 'messy_dataset_runs', ['input_fingerprint'], unique=False)
    op.create_index(op.f('ix_messy_dataset_runs_output_fingerprint'), 'messy_dataset_runs', ['output_fingerprint'], unique=False)
    op.create_index(op.f('ix_messy_dataset_runs_status'), 'messy_dataset_runs', ['status'], unique=False)
    op.create_index(op.f('ix_messy_dataset_runs_tenant_id'), 'messy_dataset_runs', ['tenant_id'], unique=False)
    op.create_table('messy_generation_control_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('messy_dataset_run_id', sa.Integer(), nullable=False),
    sa.Column('control_name', sa.String(length=120), nullable=False),
    sa.Column('clean_value', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('messy_value', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('difference_value', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('expected_difference', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('tolerance', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['messy_dataset_run_id'], ['messy_dataset_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('messy_dataset_run_id', 'control_name', name='uq_messy_control')
    )
    op.create_index(op.f('ix_messy_generation_control_totals_control_name'), 'messy_generation_control_totals', ['control_name'], unique=False)
    op.create_index(op.f('ix_messy_generation_control_totals_messy_dataset_run_id'), 'messy_generation_control_totals', ['messy_dataset_run_id'], unique=False)
    op.create_index(op.f('ix_messy_generation_control_totals_status'), 'messy_generation_control_totals', ['status'], unique=False)
    op.create_index(op.f('ix_messy_generation_control_totals_tenant_id'), 'messy_generation_control_totals', ['tenant_id'], unique=False)
    op.create_table('messy_source_files',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('messy_dataset_run_id', sa.Integer(), nullable=False),
    sa.Column('clean_generated_source_file_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('file_type', sa.String(length=100), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('sha256_checksum', sa.String(length=64), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('column_count', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['clean_generated_source_file_id'], ['generated_source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['messy_dataset_run_id'], ['messy_dataset_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('messy_dataset_run_id', 'file_type', name='uq_messy_file_type'),
    sa.UniqueConstraint('relative_path')
    )
    op.create_index(op.f('ix_messy_source_files_clean_generated_source_file_id'), 'messy_source_files', ['clean_generated_source_file_id'], unique=False)
    op.create_index(op.f('ix_messy_source_files_file_type'), 'messy_source_files', ['file_type'], unique=False)
    op.create_index(op.f('ix_messy_source_files_messy_dataset_run_id'), 'messy_source_files', ['messy_dataset_run_id'], unique=False)
    op.create_index(op.f('ix_messy_source_files_sha256_checksum'), 'messy_source_files', ['sha256_checksum'], unique=False)
    op.create_index(op.f('ix_messy_source_files_source_file_id'), 'messy_source_files', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_messy_source_files_tenant_id'), 'messy_source_files', ['tenant_id'], unique=False)
    op.create_table('data_mutations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('messy_dataset_run_id', sa.Integer(), nullable=False),
    sa.Column('source_clean_file_id', sa.Integer(), nullable=False),
    sa.Column('source_messy_file_id', sa.Integer(), nullable=True),
    sa.Column('defect_scenario_rule_id', sa.Integer(), nullable=False),
    sa.Column('defect_type', sa.String(length=100), nullable=False),
    sa.Column('target_file_type', sa.String(length=100), nullable=False),
    sa.Column('target_filename', sa.String(length=255), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=True),
    sa.Column('source_record_key', sa.String(length=255), nullable=True),
    sa.Column('target_column', sa.String(length=120), nullable=True),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('mutated_value', sa.Text(), nullable=True),
    sa.Column('mutation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('mutation_status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['defect_scenario_rule_id'], ['defect_scenario_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['messy_dataset_run_id'], ['messy_dataset_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_clean_file_id'], ['generated_source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_messy_file_id'], ['messy_source_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_mutations_defect_scenario_rule_id'), 'data_mutations', ['defect_scenario_rule_id'], unique=False)
    op.create_index(op.f('ix_data_mutations_defect_type'), 'data_mutations', ['defect_type'], unique=False)
    op.create_index(op.f('ix_data_mutations_messy_dataset_run_id'), 'data_mutations', ['messy_dataset_run_id'], unique=False)
    op.create_index(op.f('ix_data_mutations_mutation_fingerprint'), 'data_mutations', ['mutation_fingerprint'], unique=True)
    op.create_index(op.f('ix_data_mutations_mutation_status'), 'data_mutations', ['mutation_status'], unique=False)
    op.create_index(op.f('ix_data_mutations_source_clean_file_id'), 'data_mutations', ['source_clean_file_id'], unique=False)
    op.create_index(op.f('ix_data_mutations_source_messy_file_id'), 'data_mutations', ['source_messy_file_id'], unique=False)
    op.create_index(op.f('ix_data_mutations_source_record_key'), 'data_mutations', ['source_record_key'], unique=False)
    op.create_index(op.f('ix_data_mutations_source_row_number'), 'data_mutations', ['source_row_number'], unique=False)
    op.create_index(op.f('ix_data_mutations_target_column'), 'data_mutations', ['target_column'], unique=False)
    op.create_index(op.f('ix_data_mutations_target_file_type'), 'data_mutations', ['target_file_type'], unique=False)
    op.create_index(op.f('ix_data_mutations_target_filename'), 'data_mutations', ['target_filename'], unique=False)
    op.create_index(op.f('ix_data_mutations_tenant_id'), 'data_mutations', ['tenant_id'], unique=False)
    op.create_table('expected_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('messy_dataset_run_id', sa.Integer(), nullable=False),
    sa.Column('expected_exception_code', sa.String(length=120), nullable=False),
    sa.Column('expected_issue_type', sa.String(length=100), nullable=False),
    sa.Column('expected_severity', sa.String(length=30), nullable=False),
    sa.Column('expected_file_type', sa.String(length=100), nullable=False),
    sa.Column('expected_filename', sa.String(length=255), nullable=False),
    sa.Column('expected_source_row_number', sa.Integer(), nullable=True),
    sa.Column('expected_source_record_key', sa.String(length=255), nullable=True),
    sa.Column('expected_column_name', sa.String(length=120), nullable=True),
    sa.Column('related_mutation_id', sa.Integer(), nullable=True),
    sa.Column('expected_message_pattern', sa.String(length=500), nullable=False),
    sa.Column('expected_count_group', sa.String(length=120), nullable=True),
    sa.Column('expectation_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['messy_dataset_run_id'], ['messy_dataset_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['related_mutation_id'], ['data_mutations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expected_exceptions_expectation_fingerprint'), 'expected_exceptions', ['expectation_fingerprint'], unique=True)
    op.create_index(op.f('ix_expected_exceptions_expected_column_name'), 'expected_exceptions', ['expected_column_name'], unique=False)
    op.create_index(op.f('ix_expected_exceptions_expected_exception_code'), 'expected_exceptions', ['expected_exception_code'], unique=False)
    op.create_index(op.f('ix_expected_exceptions_expected_file_type'), 'expected_exceptions', ['expected_file_type'], unique=False)
    op.create_index(op.f('ix_expected_exceptions_expected_filename'), 'expected_exceptions', ['expected_filename'], unique=False)
    op.create_index(op.f('ix_expected_exceptions_expected_issue_type'), 'expected_exceptions', ['expected_issue_type'], unique=False)
    op.create_index(op.f('ix_expected_exceptions_expected_severity'), 'expected_exceptions', ['expected_severity'], unique=False)
    op.create_index(op.f('ix_expected_exceptions_expected_source_record_key'), 'expected_exceptions', ['expected_source_record_key'], unique=False)
    op.create_index(op.f('ix_expected_exceptions_expected_source_row_number'), 'expected_exceptions', ['expected_source_row_number'], unique=False)
    op.create_index(op.f('ix_expected_exceptions_messy_dataset_run_id'), 'expected_exceptions', ['messy_dataset_run_id'], unique=False)
    op.create_index(op.f('ix_expected_exceptions_related_mutation_id'), 'expected_exceptions', ['related_mutation_id'], unique=False)
    op.create_index(op.f('ix_expected_exceptions_status'), 'expected_exceptions', ['status'], unique=False)
    op.create_index(op.f('ix_expected_exceptions_tenant_id'), 'expected_exceptions', ['tenant_id'], unique=False)
    # Ignore legacy-schema drift detected by autogenerate; Phase 7 only adds its own tables.
    return
    op.alter_column('audit_event_changes', 'old_value_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_event_changes', 'new_value_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_events', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_events_entity'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_occurred'), table_name='audit_events')
    op.alter_column('canonical_record_lineage', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('counterparties', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('data_quality_issues', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('data_quality_issues_issue_fingerprint_key'), 'data_quality_issues', type_='unique')
    op.alter_column('financial_accounts', 'source_metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('financial_transactions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generated_dataset_runs', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generated_dataset_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_dataset_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_generated_dataset_tenant_generation_date'), table_name='generated_dataset_runs')
    op.drop_index(op.f('ix_generated_dataset_tenant_seed'), table_name='generated_dataset_runs')
    op.drop_index(op.f('ix_generated_dataset_tenant_version'), table_name='generated_dataset_runs')
    op.create_index(op.f('ix_generated_dataset_runs_tenant_id'), 'generated_dataset_runs', ['tenant_id'], unique=False)
    op.alter_column('generated_record_links', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generated_record_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_source_files', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generated_source_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_control_totals', 'details_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generation_control_totals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_exceptions', 'details_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generation_exceptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('normalization_control_totals', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('normalization_exceptions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('normalization_mappings', 'configuration_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('payroll_runs', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('permissions_code_key'), 'permissions', type_='unique')
    op.alter_column('pipeline_definitions', 'configuration_schema_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('pipeline_run_artifacts', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('pipeline_run_artifacts', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_pipeline_artifact_run_type'), table_name='pipeline_run_artifacts')
    op.drop_index(op.f('ix_pipeline_runs_tenant_status'), table_name='pipeline_runs')
    op.drop_constraint(op.f('roles_code_key'), 'roles', type_='unique')
    op.alter_column('source_file_column_profiles', 'sample_values_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('source_file_column_profiles', 'detected_formats_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('source_file_profiles', 'profile_metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_source_files_tenant_status'), table_name='source_files')
    op.drop_index(op.f('ix_source_systems_tenant_status'), table_name='source_systems')
    op.alter_column('tenants', 'settings_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('tenants_code_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


# This final definition intentionally replaces the autogenerate downgrade above,
# which contains unrelated legacy-schema drift.
def downgrade() -> None:
    op.drop_table("expected_exceptions")
    op.drop_table("data_mutations")
    op.drop_table("messy_source_files")
    op.drop_table("messy_generation_control_totals")
    op.drop_table("messy_dataset_runs")
    op.drop_table("defect_scenario_rules")
    op.drop_table("defect_scenarios")


def _autogenerated_downgrade_with_legacy_drift() -> None:
    # Retained for migration review only; Alembic calls the clean downgrade above.
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', [sa.literal_column('lower(email::text)')], unique=True)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenants_code_key'), 'tenants', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'settings_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_source_systems_tenant_status'), 'source_systems', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_source_files_tenant_status'), 'source_files', ['tenant_id', 'status'], unique=False)
    op.alter_column('source_file_profiles', 'profile_metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('source_file_column_profiles', 'detected_formats_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('source_file_column_profiles', 'sample_values_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('roles_code_key'), 'roles', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pipeline_runs_tenant_status'), 'pipeline_runs', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_pipeline_artifact_run_type'), 'pipeline_run_artifacts', ['pipeline_run_id', 'artifact_type'], unique=False)
    op.alter_column('pipeline_run_artifacts', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('pipeline_run_artifacts', 'file_size_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('pipeline_definitions', 'configuration_schema_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('permissions_code_key'), 'permissions', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('payroll_runs', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('payroll_entries', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('normalization_mappings', 'configuration_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('normalization_exceptions', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('normalization_control_totals', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generation_exceptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_exceptions', 'details_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generation_control_totals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_control_totals', 'details_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generated_source_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_source_files', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generated_record_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_record_links', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_generated_dataset_runs_tenant_id'), table_name='generated_dataset_runs')
    op.create_index(op.f('ix_generated_dataset_tenant_version'), 'generated_dataset_runs', ['tenant_id', 'generator_version'], unique=False)
    op.create_index(op.f('ix_generated_dataset_tenant_seed'), 'generated_dataset_runs', ['tenant_id', 'random_seed'], unique=False)
    op.create_index(op.f('ix_generated_dataset_tenant_generation_date'), 'generated_dataset_runs', ['tenant_id', 'generation_date'], unique=False)
    op.alter_column('generated_dataset_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_dataset_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_dataset_runs', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('financial_transactions', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('financial_accounts', 'source_metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('data_quality_issues_issue_fingerprint_key'), 'data_quality_issues', ['issue_fingerprint'], postgresql_nulls_not_distinct=False)
    op.alter_column('data_quality_issues', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('counterparties', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('canonical_record_lineage', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_events_tenant_occurred'), 'audit_events', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity'), 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('audit_events', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_event_changes', 'new_value_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_event_changes', 'old_value_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_expected_exceptions_tenant_id'), table_name='expected_exceptions')
    op.drop_index(op.f('ix_expected_exceptions_status'), table_name='expected_exceptions')
    op.drop_index(op.f('ix_expected_exceptions_related_mutation_id'), table_name='expected_exceptions')
    op.drop_index(op.f('ix_expected_exceptions_messy_dataset_run_id'), table_name='expected_exceptions')
    op.drop_index(op.f('ix_expected_exceptions_expected_source_row_number'), table_name='expected_exceptions')
    op.drop_index(op.f('ix_expected_exceptions_expected_source_record_key'), table_name='expected_exceptions')
    op.drop_index(op.f('ix_expected_exceptions_expected_severity'), table_name='expected_exceptions')
    op.drop_index(op.f('ix_expected_exceptions_expected_issue_type'), table_name='expected_exceptions')
    op.drop_index(op.f('ix_expected_exceptions_expected_filename'), table_name='expected_exceptions')
    op.drop_index(op.f('ix_expected_exceptions_expected_file_type'), table_name='expected_exceptions')
    op.drop_index(op.f('ix_expected_exceptions_expected_exception_code'), table_name='expected_exceptions')
    op.drop_index(op.f('ix_expected_exceptions_expected_column_name'), table_name='expected_exceptions')
    op.drop_index(op.f('ix_expected_exceptions_expectation_fingerprint'), table_name='expected_exceptions')
    op.drop_table('expected_exceptions')
    op.drop_index(op.f('ix_data_mutations_tenant_id'), table_name='data_mutations')
    op.drop_index(op.f('ix_data_mutations_target_filename'), table_name='data_mutations')
    op.drop_index(op.f('ix_data_mutations_target_file_type'), table_name='data_mutations')
    op.drop_index(op.f('ix_data_mutations_target_column'), table_name='data_mutations')
    op.drop_index(op.f('ix_data_mutations_source_row_number'), table_name='data_mutations')
    op.drop_index(op.f('ix_data_mutations_source_record_key'), table_name='data_mutations')
    op.drop_index(op.f('ix_data_mutations_source_messy_file_id'), table_name='data_mutations')
    op.drop_index(op.f('ix_data_mutations_source_clean_file_id'), table_name='data_mutations')
    op.drop_index(op.f('ix_data_mutations_mutation_status'), table_name='data_mutations')
    op.drop_index(op.f('ix_data_mutations_mutation_fingerprint'), table_name='data_mutations')
    op.drop_index(op.f('ix_data_mutations_messy_dataset_run_id'), table_name='data_mutations')
    op.drop_index(op.f('ix_data_mutations_defect_type'), table_name='data_mutations')
    op.drop_index(op.f('ix_data_mutations_defect_scenario_rule_id'), table_name='data_mutations')
    op.drop_table('data_mutations')
    op.drop_index(op.f('ix_messy_source_files_tenant_id'), table_name='messy_source_files')
    op.drop_index(op.f('ix_messy_source_files_source_file_id'), table_name='messy_source_files')
    op.drop_index(op.f('ix_messy_source_files_sha256_checksum'), table_name='messy_source_files')
    op.drop_index(op.f('ix_messy_source_files_messy_dataset_run_id'), table_name='messy_source_files')
    op.drop_index(op.f('ix_messy_source_files_file_type'), table_name='messy_source_files')
    op.drop_index(op.f('ix_messy_source_files_clean_generated_source_file_id'), table_name='messy_source_files')
    op.drop_table('messy_source_files')
    op.drop_index(op.f('ix_messy_generation_control_totals_tenant_id'), table_name='messy_generation_control_totals')
    op.drop_index(op.f('ix_messy_generation_control_totals_status'), table_name='messy_generation_control_totals')
    op.drop_index(op.f('ix_messy_generation_control_totals_messy_dataset_run_id'), table_name='messy_generation_control_totals')
    op.drop_index(op.f('ix_messy_generation_control_totals_control_name'), table_name='messy_generation_control_totals')
    op.drop_table('messy_generation_control_totals')
    op.drop_index(op.f('ix_messy_dataset_runs_tenant_id'), table_name='messy_dataset_runs')
    op.drop_index(op.f('ix_messy_dataset_runs_status'), table_name='messy_dataset_runs')
    op.drop_index(op.f('ix_messy_dataset_runs_output_fingerprint'), table_name='messy_dataset_runs')
    op.drop_index(op.f('ix_messy_dataset_runs_input_fingerprint'), table_name='messy_dataset_runs')
    op.drop_index(op.f('ix_messy_dataset_runs_defect_scenario_id'), table_name='messy_dataset_runs')
    op.drop_index(op.f('ix_messy_dataset_runs_defect_plan_fingerprint'), table_name='messy_dataset_runs')
    op.drop_index(op.f('ix_messy_dataset_runs_clean_generated_dataset_run_id'), table_name='messy_dataset_runs')
    op.drop_table('messy_dataset_runs')
    op.drop_index(op.f('ix_defect_scenario_rules_target_file_type'), table_name='defect_scenario_rules')
    op.drop_index(op.f('ix_defect_scenario_rules_severity'), table_name='defect_scenario_rules')
    op.drop_index(op.f('ix_defect_scenario_rules_rule_code'), table_name='defect_scenario_rules')
    op.drop_index(op.f('ix_defect_scenario_rules_is_enabled'), table_name='defect_scenario_rules')
    op.drop_index(op.f('ix_defect_scenario_rules_defect_type'), table_name='defect_scenario_rules')
    op.drop_index(op.f('ix_defect_scenario_rules_defect_scenario_id'), table_name='defect_scenario_rules')
    op.drop_table('defect_scenario_rules')
    op.drop_index(op.f('ix_defect_scenarios_tenant_id'), table_name='defect_scenarios')
    op.drop_index(op.f('ix_defect_scenarios_is_active'), table_name='defect_scenarios')
    op.drop_index(op.f('ix_defect_scenarios_code'), table_name='defect_scenarios')
    op.drop_table('defect_scenarios')
    # ### end Alembic commands ###
