"""add canonical financial model

Revision ID: 34851fb5b835
Revises: 496fc87bdd17
Create Date: 2026-07-14 14:47:08.267728
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '34851fb5b835'
down_revision: str | None = '496fc87bdd17'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('symbol', sa.String(length=10), nullable=False),
    sa.Column('decimal_places', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_currencies_code'), 'currencies', ['code'], unique=True)
    op.create_table('counterparties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_type', sa.String(length=30), nullable=False),
    sa.Column('canonical_name', sa.String(length=255), nullable=False),
    sa.Column('normalized_name', sa.String(length=255), nullable=False),
    sa.Column('external_reference', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'counterparty_type', 'normalized_name', name='uq_counterparty_normalized')
    )
    op.create_index(op.f('ix_counterparties_counterparty_type'), 'counterparties', ['counterparty_type'], unique=False)
    op.create_index(op.f('ix_counterparties_normalized_name'), 'counterparties', ['normalized_name'], unique=False)
    op.create_index(op.f('ix_counterparties_tenant_id'), 'counterparties', ['tenant_id'], unique=False)
    op.create_table('financial_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('account_code', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('account_subtype', sa.String(length=50), nullable=True),
    sa.Column('normal_balance', sa.String(length=10), nullable=False),
    sa.Column('parent_account_id', sa.Integer(), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_system_generated', sa.Boolean(), nullable=False),
    sa.Column('source_metadata_json', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'account_code', name='uq_financial_account_code')
    )
    op.create_index(op.f('ix_financial_accounts_account_code'), 'financial_accounts', ['account_code'], unique=False)
    op.create_index(op.f('ix_financial_accounts_account_type'), 'financial_accounts', ['account_type'], unique=False)
    op.create_index(op.f('ix_financial_accounts_tenant_id'), 'financial_accounts', ['tenant_id'], unique=False)
    op.create_table('normalization_mappings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('source_record_type', sa.String(length=50), nullable=False),
    sa.Column('target_record_type', sa.String(length=50), nullable=False),
    sa.Column('configuration_json', postgresql.JSONB(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', 'version', name='uq_normalization_mapping_version')
    )
    op.create_index(op.f('ix_normalization_mappings_code'), 'normalization_mappings', ['code'], unique=False)
    op.create_index(op.f('ix_normalization_mappings_source_record_type'), 'normalization_mappings', ['source_record_type'], unique=False)
    op.create_index(op.f('ix_normalization_mappings_tenant_id'), 'normalization_mappings', ['tenant_id'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('financial_account_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_account_code', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('institution_name', sa.String(length=255), nullable=True),
    sa.Column('masked_account_number', sa.String(length=50), nullable=True),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_system_id', 'source_account_code', name='uq_bank_source_account')
    )
    op.create_index(op.f('ix_bank_accounts_financial_account_id'), 'bank_accounts', ['financial_account_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_source_system_id'), 'bank_accounts', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_bank_accounts_status'), 'bank_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_bank_accounts_tenant_id'), 'bank_accounts', ['tenant_id'], unique=False)
    op.create_table('credit_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('financial_account_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_account_code', sa.String(length=100), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('issuer_name', sa.String(length=255), nullable=True),
    sa.Column('masked_account_number', sa.String(length=50), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_system_id', 'source_account_code', name='uq_credit_source_account')
    )
    op.create_index(op.f('ix_credit_accounts_financial_account_id'), 'credit_accounts', ['financial_account_id'], unique=False)
    op.create_index(op.f('ix_credit_accounts_source_system_id'), 'credit_accounts', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_credit_accounts_status'), 'credit_accounts', ['status'], unique=False)
    op.create_index(op.f('ix_credit_accounts_tenant_id'), 'credit_accounts', ['tenant_id'], unique=False)
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('customer_code', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('credit_limit', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'counterparty_id', name='uq_customer_counterparty'),
    sa.UniqueConstraint('tenant_id', 'customer_code', name='uq_customer_code')
    )
    op.create_index(op.f('ix_customers_tenant_id'), 'customers', ['tenant_id'], unique=False)
    op.create_table('employees',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('employee_source_id', sa.String(length=255), nullable=False),
    sa.Column('employee_number', sa.String(length=100), nullable=True),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('hire_date', sa.Date(), nullable=True),
    sa.Column('termination_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'source_system_id', 'employee_source_id', name='uq_employee_source')
    )
    op.create_index(op.f('ix_employees_employee_source_id'), 'employees', ['employee_source_id'], unique=False)
    op.create_index(op.f('ix_employees_source_system_id'), 'employees', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_employees_tenant_id'), 'employees', ['tenant_id'], unique=False)
    op.create_table('transaction_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('category_type', sa.String(length=30), nullable=False),
    sa.Column('parent_category_id', sa.Integer(), nullable=True),
    sa.Column('financial_account_id', sa.Integer(), nullable=True),
    sa.Column('is_system_category', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['financial_account_id'], ['financial_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_category_id'], ['transaction_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', name='uq_transaction_category_code')
    )
    op.create_index(op.f('ix_transaction_categories_code'), 'transaction_categories', ['code'], unique=False)
    op.create_index(op.f('ix_transaction_categories_tenant_id'), 'transaction_categories', ['tenant_id'], unique=False)
    op.create_table('vendors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('counterparty_id', sa.Integer(), nullable=False),
    sa.Column('vendor_code', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=255), nullable=False),
    sa.Column('payment_terms_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'counterparty_id', name='uq_vendor_counterparty'),
    sa.UniqueConstraint('tenant_id', 'vendor_code', name='uq_vendor_code')
    )
    op.create_index(op.f('ix_vendors_tenant_id'), 'vendors', ['tenant_id'], unique=False)
    op.create_table('financial_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.String(length=30), nullable=False),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('posted_date', sa.Date(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=24, scale=6), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('normalized_description', sa.Text(), nullable=True),
    sa.Column('reference_number', sa.String(length=255), nullable=True),
    sa.Column('counterparty_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('normalization_run_id', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('normalization_version', sa.String(length=30), nullable=False),
    sa.Column('canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['transaction_categories.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['counterparty_id'], ['counterparties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['normalization_run_id'], ['pipeline_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'canonical_hash', name='uq_canonical_transaction_hash'),
    sa.UniqueConstraint('tenant_id', 'source_file_id', 'source_row_number', 'normalization_version', name='uq_canonical_transaction_source')
    )
    op.create_index(op.f('ix_financial_transactions_canonical_hash'), 'financial_transactions', ['canonical_hash'], unique=False)
    op.create_index(op.f('ix_financial_transactions_category_id'), 'financial_transactions', ['category_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_counterparty_id'), 'financial_transactions', ['counterparty_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_normalization_run_id'), 'financial_transactions', ['normalization_run_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_source_file_id'), 'financial_transactions', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_source_system_id'), 'financial_transactions', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_status'), 'financial_transactions', ['status'], unique=False)
    op.create_index(op.f('ix_financial_transactions_tenant_id'), 'financial_transactions', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_date'), 'financial_transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_financial_transactions_transaction_type'), 'financial_transactions', ['transaction_type'], unique=False)
    op.create_table('normalization_control_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('control_name', sa.String(length=100), nullable=False),
    sa.Column('staging_value', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('canonical_value', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('difference_value', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('tolerance', sa.Numeric(precision=30, scale=6), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_run_id', 'control_name', name='uq_normalization_control')
    )
    op.create_index(op.f('ix_normalization_control_totals_pipeline_run_id'), 'normalization_control_totals', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_normalization_control_totals_source_file_id'), 'normalization_control_totals', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_normalization_control_totals_status'), 'normalization_control_totals', ['status'], unique=False)
    op.create_index(op.f('ix_normalization_control_totals_tenant_id'), 'normalization_control_totals', ['tenant_id'], unique=False)
    op.create_table('normalization_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('staging_entity_type', sa.String(length=50), nullable=False),
    sa.Column('staging_entity_id', sa.Integer(), nullable=False),
    sa.Column('exception_code', sa.String(length=100), nullable=False),
    sa.Column('exception_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=30), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=True),
    sa.Column('observed_value', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('exception_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'exception_fingerprint', name='uq_normalization_exception_fingerprint')
    )
    op.create_index(op.f('ix_normalization_exceptions_exception_code'), 'normalization_exceptions', ['exception_code'], unique=False)
    op.create_index(op.f('ix_normalization_exceptions_exception_type'), 'normalization_exceptions', ['exception_type'], unique=False)
    op.create_index(op.f('ix_normalization_exceptions_pipeline_run_id'), 'normalization_exceptions', ['pipeline_run_id'], unique=False)
    op.create_index(op.f('ix_normalization_exceptions_severity'), 'normalization_exceptions', ['severity'], unique=False)
    op.create_index(op.f('ix_normalization_exceptions_source_file_id'), 'normalization_exceptions', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_normalization_exceptions_status'), 'normalization_exceptions', ['status'], unique=False)
    op.create_index(op.f('ix_normalization_exceptions_tenant_id'), 'normalization_exceptions', ['tenant_id'], unique=False)
    op.create_table('payroll_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_source_id', sa.String(length=255), nullable=False),
    sa.Column('pay_period_start', sa.Date(), nullable=True),
    sa.Column('pay_period_end', sa.Date(), nullable=True),
    sa.Column('pay_date', sa.Date(), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('gross_pay_total', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('employee_deductions_total', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('employer_contributions_total', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('reimbursement_total', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('net_pay_total', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('normalization_version', sa.String(length=30), nullable=False),
    sa.Column('canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'canonical_hash', name='uq_payroll_run_hash'),
    sa.UniqueConstraint('tenant_id', 'source_system_id', 'payroll_run_source_id', 'normalization_version', name='uq_payroll_run_source')
    )
    op.create_index(op.f('ix_payroll_runs_canonical_hash'), 'payroll_runs', ['canonical_hash'], unique=False)
    op.create_index(op.f('ix_payroll_runs_pay_date'), 'payroll_runs', ['pay_date'], unique=False)
    op.create_index(op.f('ix_payroll_runs_source_file_id'), 'payroll_runs', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_payroll_runs_source_system_id'), 'payroll_runs', ['source_system_id'], unique=False)
    op.create_index(op.f('ix_payroll_runs_tenant_id'), 'payroll_runs', ['tenant_id'], unique=False)
    op.create_table('canonical_record_lineage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('canonical_entity_type', sa.String(length=50), nullable=False),
    sa.Column('canonical_entity_id', sa.Integer(), nullable=False),
    sa.Column('source_system_id', sa.Integer(), nullable=False),
    sa.Column('source_file_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('raw_source_row_id', sa.Integer(), nullable=False),
    sa.Column('staging_entity_type', sa.String(length=50), nullable=False),
    sa.Column('staging_entity_id', sa.Integer(), nullable=False),
    sa.Column('source_row_number', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.String(length=255), nullable=True),
    sa.Column('transformation_name', sa.String(length=100), nullable=False),
    sa.Column('transformation_version', sa.String(length=30), nullable=False),
    sa.Column('mapping_code', sa.String(length=100), nullable=False),
    sa.Column('mapping_version', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['raw_source_row_id'], ['raw_source_rows.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['source_system_id'], ['source_systems.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'canonical_entity_type', 'canonical_entity_id', 'staging_entity_type', 'staging_entity_id', 'transformation_version', name='uq_canonical_lineage')
    )
    op.create_index(op.f('ix_canonical_record_lineage_canonical_entity_id'), 'canonical_record_lineage', ['canonical_entity_id'], unique=False)
    op.create_index(op.f('ix_canonical_record_lineage_canonical_entity_type'), 'canonical_record_lineage', ['canonical_entity_type'], unique=False)
    op.create_index(op.f('ix_canonical_record_lineage_source_file_id'), 'canonical_record_lineage', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_canonical_record_lineage_staging_entity_id'), 'canonical_record_lineage', ['staging_entity_id'], unique=False)
    op.create_index(op.f('ix_canonical_record_lineage_staging_entity_type'), 'canonical_record_lineage', ['staging_entity_type'], unique=False)
    op.create_index(op.f('ix_canonical_record_lineage_tenant_id'), 'canonical_record_lineage', ['tenant_id'], unique=False)
    op.create_table('bank_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('financial_transaction_id', sa.Integer(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('staging_bank_transaction_id', sa.Integer(), nullable=False),
    sa.Column('debit_amount', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('credit_amount', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('running_balance', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('transaction_direction', sa.String(length=20), nullable=False),
    sa.Column('is_internal_transfer', sa.Boolean(), nullable=False),
    sa.Column('normalization_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_transaction_id'], ['financial_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staging_bank_transaction_id'], ['staging_bank_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_transaction_id'),
    sa.UniqueConstraint('tenant_id', 'staging_bank_transaction_id', 'normalization_version', name='uq_bank_normalized_staging')
    )
    op.create_index(op.f('ix_bank_transactions_bank_account_id'), 'bank_transactions', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_staging_bank_transaction_id'), 'bank_transactions', ['staging_bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_bank_transactions_tenant_id'), 'bank_transactions', ['tenant_id'], unique=False)
    op.create_table('credit_card_transactions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('financial_transaction_id', sa.Integer(), nullable=False),
    sa.Column('credit_account_id', sa.Integer(), nullable=False),
    sa.Column('staging_credit_card_transaction_id', sa.Integer(), nullable=False),
    sa.Column('merchant_counterparty_id', sa.Integer(), nullable=True),
    sa.Column('purchase_amount', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('refund_amount', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('transaction_direction', sa.String(length=20), nullable=False),
    sa.Column('normalization_version', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['credit_account_id'], ['credit_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['financial_transaction_id'], ['financial_transactions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['merchant_counterparty_id'], ['counterparties.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staging_credit_card_transaction_id'], ['staging_credit_card_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('financial_transaction_id'),
    sa.UniqueConstraint('tenant_id', 'staging_credit_card_transaction_id', 'normalization_version', name='uq_card_normalized_staging')
    )
    op.create_index(op.f('ix_credit_card_transactions_credit_account_id'), 'credit_card_transactions', ['credit_account_id'], unique=False)
    op.create_index(op.f('ix_credit_card_transactions_staging_credit_card_transaction_id'), 'credit_card_transactions', ['staging_credit_card_transaction_id'], unique=False)
    op.create_index(op.f('ix_credit_card_transactions_tenant_id'), 'credit_card_transactions', ['tenant_id'], unique=False)
    op.create_table('payroll_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('payroll_run_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('staging_payroll_summary_id', sa.Integer(), nullable=True),
    sa.Column('staging_payroll_detail_id', sa.Integer(), nullable=True),
    sa.Column('gross_pay', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('regular_pay', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('overtime_pay', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('bonus_pay', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('reimbursement_amount', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('employee_tax', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('employee_deduction', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('employer_tax', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('employer_contribution', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('net_pay', sa.Numeric(precision=24, scale=6), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('normalization_version', sa.String(length=30), nullable=False),
    sa.Column('canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['payroll_run_id'], ['payroll_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staging_payroll_detail_id'], ['staging_payroll_details.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['staging_payroll_summary_id'], ['staging_payroll_summaries.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('staging_payroll_detail_id'),
    sa.UniqueConstraint('staging_payroll_summary_id'),
    sa.UniqueConstraint('tenant_id', 'canonical_hash', name='uq_payroll_entry_hash')
    )
    op.create_index(op.f('ix_payroll_entries_canonical_hash'), 'payroll_entries', ['canonical_hash'], unique=False)
    op.create_index(op.f('ix_payroll_entries_employee_id'), 'payroll_entries', ['employee_id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_payroll_run_id'), 'payroll_entries', ['payroll_run_id'], unique=False)
    op.create_index(op.f('ix_payroll_entries_tenant_id'), 'payroll_entries', ['tenant_id'], unique=False)
    op.execute(
        """
        INSERT INTO permissions (code, name)
        VALUES
          ('normalization.execute', 'Normalization Execute'),
          ('canonical_records.view', 'Canonical Records View'),
          ('canonical_lineage.view', 'Canonical Lineage View'),
          ('normalization_exceptions.view', 'Normalization Exceptions View'),
          ('normalization_exceptions.manage', 'Normalization Exceptions Manage'),
          ('normalization_control_totals.view', 'Normalization Control Totals View')
        ON CONFLICT (code) DO NOTHING
        """
    )
    op.execute(
        """
        INSERT INTO role_permissions (role_id, permission_id)
        SELECT r.id, p.id FROM roles r CROSS JOIN permissions p
        WHERE (
          r.code IN ('platform_admin', 'cfo_user', 'finance_analyst')
          OR (r.code = 'client_viewer' AND p.code = 'canonical_records.view')
        )
        AND p.code IN (
          'normalization.execute', 'canonical_records.view', 'canonical_lineage.view',
          'normalization_exceptions.view', 'normalization_exceptions.manage',
          'normalization_control_totals.view'
        )
        AND NOT (r.code = 'finance_analyst' AND p.code = 'normalization_exceptions.manage')
        ON CONFLICT (role_id, permission_id) DO NOTHING
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM role_permissions WHERE permission_id IN (
          SELECT id FROM permissions WHERE code IN (
            'normalization.execute', 'canonical_records.view', 'canonical_lineage.view',
            'normalization_exceptions.view', 'normalization_exceptions.manage',
            'normalization_control_totals.view'
          )
        )
        """
    )
    op.execute(
        """
        DELETE FROM permissions WHERE code IN (
          'normalization.execute', 'canonical_records.view', 'canonical_lineage.view',
          'normalization_exceptions.view', 'normalization_exceptions.manage',
          'normalization_control_totals.view'
        )
        """
    )
    op.drop_index(op.f('ix_payroll_entries_tenant_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_payroll_run_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_employee_id'), table_name='payroll_entries')
    op.drop_index(op.f('ix_payroll_entries_canonical_hash'), table_name='payroll_entries')
    op.drop_table('payroll_entries')
    op.drop_index(op.f('ix_credit_card_transactions_tenant_id'), table_name='credit_card_transactions')
    op.drop_index(op.f('ix_credit_card_transactions_staging_credit_card_transaction_id'), table_name='credit_card_transactions')
    op.drop_index(op.f('ix_credit_card_transactions_credit_account_id'), table_name='credit_card_transactions')
    op.drop_table('credit_card_transactions')
    op.drop_index(op.f('ix_bank_transactions_tenant_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_staging_bank_transaction_id'), table_name='bank_transactions')
    op.drop_index(op.f('ix_bank_transactions_bank_account_id'), table_name='bank_transactions')
    op.drop_table('bank_transactions')
    op.drop_index(op.f('ix_canonical_record_lineage_tenant_id'), table_name='canonical_record_lineage')
    op.drop_index(op.f('ix_canonical_record_lineage_staging_entity_type'), table_name='canonical_record_lineage')
    op.drop_index(op.f('ix_canonical_record_lineage_staging_entity_id'), table_name='canonical_record_lineage')
    op.drop_index(op.f('ix_canonical_record_lineage_source_file_id'), table_name='canonical_record_lineage')
    op.drop_index(op.f('ix_canonical_record_lineage_canonical_entity_type'), table_name='canonical_record_lineage')
    op.drop_index(op.f('ix_canonical_record_lineage_canonical_entity_id'), table_name='canonical_record_lineage')
    op.drop_table('canonical_record_lineage')
    op.drop_index(op.f('ix_payroll_runs_tenant_id'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_source_system_id'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_source_file_id'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_pay_date'), table_name='payroll_runs')
    op.drop_index(op.f('ix_payroll_runs_canonical_hash'), table_name='payroll_runs')
    op.drop_table('payroll_runs')
    op.drop_index(op.f('ix_normalization_exceptions_tenant_id'), table_name='normalization_exceptions')
    op.drop_index(op.f('ix_normalization_exceptions_status'), table_name='normalization_exceptions')
    op.drop_index(op.f('ix_normalization_exceptions_source_file_id'), table_name='normalization_exceptions')
    op.drop_index(op.f('ix_normalization_exceptions_severity'), table_name='normalization_exceptions')
    op.drop_index(op.f('ix_normalization_exceptions_pipeline_run_id'), table_name='normalization_exceptions')
    op.drop_index(op.f('ix_normalization_exceptions_exception_type'), table_name='normalization_exceptions')
    op.drop_index(op.f('ix_normalization_exceptions_exception_code'), table_name='normalization_exceptions')
    op.drop_table('normalization_exceptions')
    op.drop_index(op.f('ix_normalization_control_totals_tenant_id'), table_name='normalization_control_totals')
    op.drop_index(op.f('ix_normalization_control_totals_status'), table_name='normalization_control_totals')
    op.drop_index(op.f('ix_normalization_control_totals_source_file_id'), table_name='normalization_control_totals')
    op.drop_index(op.f('ix_normalization_control_totals_pipeline_run_id'), table_name='normalization_control_totals')
    op.drop_table('normalization_control_totals')
    op.drop_index(op.f('ix_financial_transactions_transaction_type'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_transaction_date'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_tenant_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_status'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_source_system_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_source_file_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_normalization_run_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_counterparty_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_category_id'), table_name='financial_transactions')
    op.drop_index(op.f('ix_financial_transactions_canonical_hash'), table_name='financial_transactions')
    op.drop_table('financial_transactions')
    op.drop_index(op.f('ix_vendors_tenant_id'), table_name='vendors')
    op.drop_table('vendors')
    op.drop_index(op.f('ix_transaction_categories_tenant_id'), table_name='transaction_categories')
    op.drop_index(op.f('ix_transaction_categories_code'), table_name='transaction_categories')
    op.drop_table('transaction_categories')
    op.drop_index(op.f('ix_employees_tenant_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_source_system_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_source_id'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_customers_tenant_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_credit_accounts_tenant_id'), table_name='credit_accounts')
    op.drop_index(op.f('ix_credit_accounts_status'), table_name='credit_accounts')
    op.drop_index(op.f('ix_credit_accounts_source_system_id'), table_name='credit_accounts')
    op.drop_index(op.f('ix_credit_accounts_financial_account_id'), table_name='credit_accounts')
    op.drop_table('credit_accounts')
    op.drop_index(op.f('ix_bank_accounts_tenant_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_status'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_source_system_id'), table_name='bank_accounts')
    op.drop_index(op.f('ix_bank_accounts_financial_account_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_normalization_mappings_tenant_id'), table_name='normalization_mappings')
    op.drop_index(op.f('ix_normalization_mappings_source_record_type'), table_name='normalization_mappings')
    op.drop_index(op.f('ix_normalization_mappings_code'), table_name='normalization_mappings')
    op.drop_table('normalization_mappings')
    op.drop_index(op.f('ix_financial_accounts_tenant_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_account_type'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_account_code'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    op.drop_index(op.f('ix_counterparties_tenant_id'), table_name='counterparties')
    op.drop_index(op.f('ix_counterparties_normalized_name'), table_name='counterparties')
    op.drop_index(op.f('ix_counterparties_counterparty_type'), table_name='counterparties')
    op.drop_table('counterparties')
    op.drop_index(op.f('ix_currencies_code'), table_name='currencies')
    op.drop_table('currencies')
    # ### end Alembic commands ###
