"""add bank ledger reconciliation

Revision ID: 240ac0e252e1
Revises: a8d4c2e901f7
Create Date: 2026-07-14 22:55:30.661186
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '240ac0e252e1'
down_revision: str | None = 'a8d4c2e901f7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reconciliation_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=120), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('version', sa.String(length=30), nullable=False),
    sa.Column('rule_type', sa.String(length=50), nullable=False),
    sa.Column('execution_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('auto_accept', sa.Boolean(), nullable=False),
    sa.Column('minimum_confidence', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('configuration_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'code', 'version', name='uq_reconciliation_rule_version')
    )
    op.create_index(op.f('ix_reconciliation_rules_code'), 'reconciliation_rules', ['code'], unique=False)
    op.create_index(op.f('ix_reconciliation_rules_is_active'), 'reconciliation_rules', ['is_active'], unique=False)
    op.create_index(op.f('ix_reconciliation_rules_rule_type'), 'reconciliation_rules', ['rule_type'], unique=False)
    op.create_index(op.f('ix_reconciliation_rules_tenant_id'), 'reconciliation_rules', ['tenant_id'], unique=False)
    op.create_table('bank_ledger_reconciliation_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('pipeline_run_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_version', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('date_from', sa.Date(), nullable=False),
    sa.Column('date_to', sa.Date(), nullable=False),
    sa.Column('bank_account_id', sa.Integer(), nullable=False),
    sa.Column('generated_source_file_id', sa.Integer(), nullable=False),
    sa.Column('validation_run_id', sa.Integer(), nullable=True),
    sa.Column('included_bank_transaction_count', sa.Integer(), nullable=False),
    sa.Column('included_ledger_line_count', sa.Integer(), nullable=False),
    sa.Column('automatically_matched_count', sa.Integer(), nullable=False),
    sa.Column('suggested_match_count', sa.Integer(), nullable=False),
    sa.Column('partially_matched_count', sa.Integer(), nullable=False),
    sa.Column('unmatched_bank_count', sa.Integer(), nullable=False),
    sa.Column('unmatched_ledger_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('reversal_count', sa.Integer(), nullable=False),
    sa.Column('exception_count', sa.Integer(), nullable=False),
    sa.Column('total_bank_amount', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('total_ledger_amount', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('total_matched_amount', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('total_unmatched_bank_amount', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('total_unmatched_ledger_amount', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('reconciliation_rate', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('input_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('ruleset_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_account_id'], ['bank_accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['generated_source_file_id'], ['generated_source_files.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['pipeline_run_id'], ['pipeline_runs.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['validation_run_id'], ['validation_runs.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('pipeline_run_id'),
    sa.UniqueConstraint('tenant_id', 'input_fingerprint', 'ruleset_fingerprint', 'reconciliation_version', name='uq_bank_ledger_reconciliation_input')
    )
    op.create_index(op.f('ix_bank_ledger_reconciliation_runs_bank_account_id'), 'bank_ledger_reconciliation_runs', ['bank_account_id'], unique=False)
    op.create_index(op.f('ix_bank_ledger_reconciliation_runs_date_from'), 'bank_ledger_reconciliation_runs', ['date_from'], unique=False)
    op.create_index(op.f('ix_bank_ledger_reconciliation_runs_date_to'), 'bank_ledger_reconciliation_runs', ['date_to'], unique=False)
    op.create_index(op.f('ix_bank_ledger_reconciliation_runs_input_fingerprint'), 'bank_ledger_reconciliation_runs', ['input_fingerprint'], unique=False)
    op.create_index(op.f('ix_bank_ledger_reconciliation_runs_reconciliation_version'), 'bank_ledger_reconciliation_runs', ['reconciliation_version'], unique=False)
    op.create_index(op.f('ix_bank_ledger_reconciliation_runs_ruleset_fingerprint'), 'bank_ledger_reconciliation_runs', ['ruleset_fingerprint'], unique=False)
    op.create_index(op.f('ix_bank_ledger_reconciliation_runs_status'), 'bank_ledger_reconciliation_runs', ['status'], unique=False)
    op.create_index(op.f('ix_bank_ledger_reconciliation_runs_tenant_id'), 'bank_ledger_reconciliation_runs', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_bank_ledger_reconciliation_runs_validation_run_id'), 'bank_ledger_reconciliation_runs', ['validation_run_id'], unique=False)
    op.create_table('reconciliation_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_run_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_rule_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_version', sa.String(length=30), nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=True),
    sa.Column('ledger_record_id', sa.String(length=255), nullable=True),
    sa.Column('match_group_key', sa.String(length=255), nullable=True),
    sa.Column('candidate_type', sa.String(length=40), nullable=False),
    sa.Column('amount_difference', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('date_difference_days', sa.Integer(), nullable=True),
    sa.Column('reference_score', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('description_score', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('amount_score', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('date_score', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('total_confidence', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('candidate_status', sa.String(length=40), nullable=False),
    sa.Column('reason_json', sa.JSON(), nullable=False),
    sa.Column('candidate_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reconciliation_rule_id'], ['reconciliation_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['bank_ledger_reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_run_id', 'candidate_fingerprint', name='uq_reconciliation_candidate')
    )
    op.create_index(op.f('ix_reconciliation_candidates_bank_transaction_id'), 'reconciliation_candidates', ['bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_candidate_fingerprint'), 'reconciliation_candidates', ['candidate_fingerprint'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_candidate_status'), 'reconciliation_candidates', ['candidate_status'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_candidate_type'), 'reconciliation_candidates', ['candidate_type'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_ledger_record_id'), 'reconciliation_candidates', ['ledger_record_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_match_group_key'), 'reconciliation_candidates', ['match_group_key'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_reconciliation_rule_id'), 'reconciliation_candidates', ['reconciliation_rule_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_reconciliation_run_id'), 'reconciliation_candidates', ['reconciliation_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_tenant_id'), 'reconciliation_candidates', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_candidates_total_confidence'), 'reconciliation_candidates', ['total_confidence'], unique=False)
    op.create_table('reconciliation_control_totals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_run_id', sa.Integer(), nullable=False),
    sa.Column('control_name', sa.String(length=120), nullable=False),
    sa.Column('source_value', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('matched_value', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('unmatched_value', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('difference_value', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('tolerance', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['bank_ledger_reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_run_id', 'control_name', name='uq_reconciliation_control')
    )
    op.create_index(op.f('ix_reconciliation_control_totals_control_name'), 'reconciliation_control_totals', ['control_name'], unique=False)
    op.create_index(op.f('ix_reconciliation_control_totals_reconciliation_run_id'), 'reconciliation_control_totals', ['reconciliation_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_control_totals_status'), 'reconciliation_control_totals', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_control_totals_tenant_id'), 'reconciliation_control_totals', ['tenant_id'], unique=False)
    op.create_table('reconciliation_match_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_run_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_rule_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_version', sa.String(length=30), nullable=False),
    sa.Column('group_type', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('matched_amount', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('bank_total', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('ledger_total', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('difference_amount', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('auto_accepted', sa.Boolean(), nullable=False),
    sa.Column('reviewed_by_user_id', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('group_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_rule_id'], ['reconciliation_rules.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['bank_ledger_reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_run_id', 'group_fingerprint', name='uq_reconciliation_group')
    )
    op.create_index(op.f('ix_reconciliation_match_groups_auto_accepted'), 'reconciliation_match_groups', ['auto_accepted'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_groups_confidence'), 'reconciliation_match_groups', ['confidence'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_groups_group_fingerprint'), 'reconciliation_match_groups', ['group_fingerprint'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_groups_group_type'), 'reconciliation_match_groups', ['group_type'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_groups_reconciliation_run_id'), 'reconciliation_match_groups', ['reconciliation_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_groups_status'), 'reconciliation_match_groups', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_match_groups_tenant_id'), 'reconciliation_match_groups', ['tenant_id'], unique=False)
    op.create_table('reconciliation_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_run_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_version', sa.String(length=30), nullable=False),
    sa.Column('report_type', sa.String(length=80), nullable=False),
    sa.Column('relative_path', sa.String(length=500), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['bank_ledger_reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_run_id', 'report_type', name='uq_reconciliation_report'),
    sa.UniqueConstraint('relative_path')
    )
    op.create_index(op.f('ix_reconciliation_reports_checksum'), 'reconciliation_reports', ['checksum'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_reconciliation_run_id'), 'reconciliation_reports', ['reconciliation_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_report_type'), 'reconciliation_reports', ['report_type'], unique=False)
    op.create_index(op.f('ix_reconciliation_reports_tenant_id'), 'reconciliation_reports', ['tenant_id'], unique=False)
    op.create_table('reconciliation_allocations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_run_id', sa.Integer(), nullable=False),
    sa.Column('match_group_id', sa.Integer(), nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=False),
    sa.Column('ledger_record_id', sa.String(length=255), nullable=False),
    sa.Column('allocated_amount', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('allocation_direction', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['match_group_id'], ['reconciliation_match_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['bank_ledger_reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_group_id', 'bank_transaction_id', 'ledger_record_id', name='uq_reconciliation_allocation')
    )
    op.create_index(op.f('ix_reconciliation_allocations_bank_transaction_id'), 'reconciliation_allocations', ['bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_allocations_ledger_record_id'), 'reconciliation_allocations', ['ledger_record_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_allocations_match_group_id'), 'reconciliation_allocations', ['match_group_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_allocations_reconciliation_run_id'), 'reconciliation_allocations', ['reconciliation_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_allocations_tenant_id'), 'reconciliation_allocations', ['tenant_id'], unique=False)
    op.create_table('reconciliation_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_run_id', sa.Integer(), nullable=False),
    sa.Column('match_group_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=False),
    sa.Column('decision', sa.String(length=30), nullable=False),
    sa.Column('previous_status', sa.String(length=40), nullable=False),
    sa.Column('new_status', sa.String(length=40), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.String(length=1000), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['match_group_id'], ['reconciliation_match_groups.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['bank_ledger_reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_decisions_actor_user_id'), 'reconciliation_decisions', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_decisions_decision'), 'reconciliation_decisions', ['decision'], unique=False)
    op.create_index(op.f('ix_reconciliation_decisions_match_group_id'), 'reconciliation_decisions', ['match_group_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_decisions_reconciliation_run_id'), 'reconciliation_decisions', ['reconciliation_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_decisions_tenant_id'), 'reconciliation_decisions', ['tenant_id'], unique=False)
    op.create_table('reconciliation_exceptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_run_id', sa.Integer(), nullable=False),
    sa.Column('exception_code', sa.String(length=120), nullable=False),
    sa.Column('exception_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=True),
    sa.Column('ledger_record_id', sa.String(length=255), nullable=True),
    sa.Column('match_group_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('observed_value', sa.Text(), nullable=True),
    sa.Column('expected_value', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('exception_fingerprint', sa.String(length=64), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['match_group_id'], ['reconciliation_match_groups.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['bank_ledger_reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reconciliation_run_id', 'exception_fingerprint', name='uq_reconciliation_exception')
    )
    op.create_index(op.f('ix_reconciliation_exceptions_bank_transaction_id'), 'reconciliation_exceptions', ['bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_exception_code'), 'reconciliation_exceptions', ['exception_code'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_exception_fingerprint'), 'reconciliation_exceptions', ['exception_fingerprint'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_exception_type'), 'reconciliation_exceptions', ['exception_type'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_ledger_record_id'), 'reconciliation_exceptions', ['ledger_record_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_reconciliation_run_id'), 'reconciliation_exceptions', ['reconciliation_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_severity'), 'reconciliation_exceptions', ['severity'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_status'), 'reconciliation_exceptions', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_exceptions_tenant_id'), 'reconciliation_exceptions', ['tenant_id'], unique=False)
    op.create_table('reconciliation_matches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('reconciliation_run_id', sa.Integer(), nullable=False),
    sa.Column('match_group_id', sa.Integer(), nullable=False),
    sa.Column('bank_transaction_id', sa.Integer(), nullable=False),
    sa.Column('ledger_record_id', sa.String(length=255), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=True),
    sa.Column('matched_amount', sa.Numeric(precision=30, scale=6), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=8, scale=6), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('rule_code', sa.String(length=120), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['bank_transaction_id'], ['bank_transactions.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['candidate_id'], ['reconciliation_candidates.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['match_group_id'], ['reconciliation_match_groups.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reconciliation_run_id'], ['bank_ledger_reconciliation_runs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('match_group_id', 'bank_transaction_id', 'ledger_record_id', name='uq_reconciliation_match_member')
    )
    op.create_index(op.f('ix_reconciliation_matches_bank_transaction_id'), 'reconciliation_matches', ['bank_transaction_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_ledger_record_id'), 'reconciliation_matches', ['ledger_record_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_match_group_id'), 'reconciliation_matches', ['match_group_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_reconciliation_run_id'), 'reconciliation_matches', ['reconciliation_run_id'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_rule_code'), 'reconciliation_matches', ['rule_code'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_status'), 'reconciliation_matches', ['status'], unique=False)
    op.create_index(op.f('ix_reconciliation_matches_tenant_id'), 'reconciliation_matches', ['tenant_id'], unique=False)
    # Ignore unrelated legacy-schema drift detected by autogenerate.
    return
    op.alter_column('audit_event_changes', 'old_value_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_event_changes', 'new_value_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('audit_events', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_audit_events_entity'), table_name='audit_events')
    op.drop_index(op.f('ix_audit_events_tenant_occurred'), table_name='audit_events')
    op.alter_column('canonical_record_lineage', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('counterparties', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('data_quality_issues', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('data_quality_issues_issue_fingerprint_key'), 'data_quality_issues', type_='unique')
    op.alter_column('financial_accounts', 'source_metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('financial_transactions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generated_dataset_runs', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generated_dataset_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_dataset_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_generated_dataset_tenant_generation_date'), table_name='generated_dataset_runs')
    op.drop_index(op.f('ix_generated_dataset_tenant_seed'), table_name='generated_dataset_runs')
    op.drop_index(op.f('ix_generated_dataset_tenant_version'), table_name='generated_dataset_runs')
    op.create_index(op.f('ix_generated_dataset_runs_tenant_id'), 'generated_dataset_runs', ['tenant_id'], unique=False)
    op.alter_column('generated_record_links', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generated_record_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_source_files', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generated_source_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_control_totals', 'details_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generation_control_totals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_exceptions', 'details_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('generation_exceptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('normalization_control_totals', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('normalization_exceptions', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('normalization_mappings', 'configuration_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False)
    op.alter_column('payroll_entries', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('payroll_runs', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('permissions_code_key'), 'permissions', type_='unique')
    op.alter_column('pipeline_definitions', 'configuration_schema_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('pipeline_run_artifacts', 'file_size_bytes',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('pipeline_run_artifacts', 'metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_pipeline_artifact_run_type'), table_name='pipeline_run_artifacts')
    op.drop_index(op.f('ix_pipeline_runs_tenant_status'), table_name='pipeline_runs')
    op.drop_constraint(op.f('roles_code_key'), 'roles', type_='unique')
    op.alter_column('source_file_column_profiles', 'sample_values_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('source_file_column_profiles', 'detected_formats_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('source_file_profiles', 'profile_metadata_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_index(op.f('ix_source_files_tenant_status'), table_name='source_files')
    op.drop_index(op.f('ix_source_systems_tenant_status'), table_name='source_systems')
    op.alter_column('tenants', 'settings_json',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.drop_constraint(op.f('tenants_code_key'), 'tenants', type_='unique')
    op.drop_constraint(op.f('users_email_key'), 'users', type_='unique')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_validation_issue_history_validation_issue_id'), 'validation_issue_history', ['validation_issue_id'], unique=False)
    op.create_index(op.f('ix_validation_issues_column_name'), 'validation_issues', ['column_name'], unique=False)
    op.create_index(op.f('ix_validation_issues_entity_key'), 'validation_issues', ['entity_key'], unique=False)
    op.create_index(op.f('ix_validation_issues_issue_fingerprint'), 'validation_issues', ['issue_fingerprint'], unique=False)
    op.create_index(op.f('ix_validation_issues_issue_type'), 'validation_issues', ['issue_type'], unique=False)
    op.create_index(op.f('ix_validation_issues_row_number'), 'validation_issues', ['row_number'], unique=False)
    op.create_index(op.f('ix_validation_issues_source_file_id'), 'validation_issues', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_validation_issues_validation_version'), 'validation_issues', ['validation_version'], unique=False)
    op.create_index(op.f('ix_validation_reports_sha256_checksum'), 'validation_reports', ['sha256_checksum'], unique=False)
    op.create_index(op.f('ix_validation_reports_tenant_id'), 'validation_reports', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_validation_rules_is_enabled'), 'validation_rules', ['is_enabled'], unique=False)
    op.create_index(op.f('ix_validation_rules_target_entity'), 'validation_rules', ['target_entity'], unique=False)
    op.create_index(op.f('ix_validation_run_results_tenant_id'), 'validation_run_results', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_generated_dataset_run_id'), 'validation_runs', ['generated_dataset_run_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_messy_dataset_run_id'), 'validation_runs', ['messy_dataset_run_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_rule_set_id'), 'validation_runs', ['rule_set_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_source_file_id'), 'validation_runs', ['source_file_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_target_id'), 'validation_runs', ['target_id'], unique=False)
    op.create_index(op.f('ix_validation_runs_validation_version'), 'validation_runs', ['validation_version'], unique=False)
    op.create_index(op.f('ix_validation_statistics_dimension_key'), 'validation_statistics', ['dimension_key'], unique=False)
    op.create_index(op.f('ix_validation_statistics_tenant_id'), 'validation_statistics', ['tenant_id'], unique=False)
    op.drop_constraint(op.f('validation_summaries_summary_fingerprint_key'), 'validation_summaries', type_='unique')
    op.create_index(op.f('ix_validation_summaries_overall_status'), 'validation_summaries', ['overall_status'], unique=False)
    op.create_index(op.f('ix_validation_summaries_summary_fingerprint'), 'validation_summaries', ['summary_fingerprint'], unique=True)
    op.create_index(op.f('ix_validation_summaries_tenant_id'), 'validation_summaries', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    op.drop_table("reconciliation_matches")
    op.drop_table("reconciliation_exceptions")
    op.drop_table("reconciliation_decisions")
    op.drop_table("reconciliation_allocations")
    op.drop_table("reconciliation_reports")
    op.drop_table("reconciliation_match_groups")
    op.drop_table("reconciliation_control_totals")
    op.drop_table("reconciliation_candidates")
    op.drop_table("bank_ledger_reconciliation_runs")
    op.drop_table("reconciliation_rules")


def _autogenerated_downgrade_with_legacy_drift() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_validation_summaries_tenant_id'), table_name='validation_summaries')
    op.drop_index(op.f('ix_validation_summaries_summary_fingerprint'), table_name='validation_summaries')
    op.drop_index(op.f('ix_validation_summaries_overall_status'), table_name='validation_summaries')
    op.create_unique_constraint(op.f('validation_summaries_summary_fingerprint_key'), 'validation_summaries', ['summary_fingerprint'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_validation_statistics_tenant_id'), table_name='validation_statistics')
    op.drop_index(op.f('ix_validation_statistics_dimension_key'), table_name='validation_statistics')
    op.drop_index(op.f('ix_validation_runs_validation_version'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_target_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_source_file_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_rule_set_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_messy_dataset_run_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_runs_generated_dataset_run_id'), table_name='validation_runs')
    op.drop_index(op.f('ix_validation_run_results_tenant_id'), table_name='validation_run_results')
    op.drop_index(op.f('ix_validation_rules_target_entity'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_rules_is_enabled'), table_name='validation_rules')
    op.drop_index(op.f('ix_validation_reports_tenant_id'), table_name='validation_reports')
    op.drop_index(op.f('ix_validation_reports_sha256_checksum'), table_name='validation_reports')
    op.drop_index(op.f('ix_validation_issues_validation_version'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_source_file_id'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_row_number'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_issue_type'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_issue_fingerprint'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_entity_key'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issues_column_name'), table_name='validation_issues')
    op.drop_index(op.f('ix_validation_issue_history_validation_issue_id'), table_name='validation_issue_history')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', [sa.literal_column('lower(email::text)')], unique=True)
    op.create_unique_constraint(op.f('users_email_key'), 'users', ['email'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('tenants_code_key'), 'tenants', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('tenants', 'settings_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_source_systems_tenant_status'), 'source_systems', ['tenant_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_source_files_tenant_status'), 'source_files', ['tenant_id', 'status'], unique=False)
    op.alter_column('source_file_profiles', 'profile_metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('source_file_column_profiles', 'detected_formats_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('source_file_column_profiles', 'sample_values_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('roles_code_key'), 'roles', ['code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_pipeline_runs_tenant_status'), 'pipeline_runs', ['tenant_id', 'status'], unique=False)
    op.create_index(op.f('ix_pipeline_artifact_run_type'), 'pipeline_run_artifacts', ['pipeline_run_id', 'artifact_type'], unique=False)
    op.alter_column('pipeline_run_artifacts', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('pipeline_run_artifacts', 'file_size_bytes',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=True)
    op.alter_column('pipeline_definitions', 'configuration_schema_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('permissions_code_key'), 'permissions', ['code'], postgresql_nulls_not_distinct=False)
    op.alter_column('payroll_runs', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('payroll_entries', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('normalization_mappings', 'configuration_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False)
    op.alter_column('normalization_exceptions', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('normalization_control_totals', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generation_exceptions', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_exceptions', 'details_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generation_control_totals', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generation_control_totals', 'details_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generated_source_files', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_source_files', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('generated_record_links', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_record_links', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_generated_dataset_runs_tenant_id'), table_name='generated_dataset_runs')
    op.create_index(op.f('ix_generated_dataset_tenant_version'), 'generated_dataset_runs', ['tenant_id', 'generator_version'], unique=False)
    op.create_index(op.f('ix_generated_dataset_tenant_seed'), 'generated_dataset_runs', ['tenant_id', 'random_seed'], unique=False)
    op.create_index(op.f('ix_generated_dataset_tenant_generation_date'), 'generated_dataset_runs', ['tenant_id', 'generation_date'], unique=False)
    op.alter_column('generated_dataset_runs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_dataset_runs', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('generated_dataset_runs', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('financial_transactions', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('financial_accounts', 'source_metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_unique_constraint(op.f('data_quality_issues_issue_fingerprint_key'), 'data_quality_issues', ['issue_fingerprint'], postgresql_nulls_not_distinct=False)
    op.alter_column('data_quality_issues', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('counterparties', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('canonical_record_lineage', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.create_index(op.f('ix_audit_events_tenant_occurred'), 'audit_events', ['tenant_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_audit_events_entity'), 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('audit_events', 'metadata_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_event_changes', 'new_value_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('audit_event_changes', 'old_value_json',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_index(op.f('ix_reconciliation_matches_tenant_id'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_status'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_rule_code'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_reconciliation_run_id'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_match_group_id'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_ledger_record_id'), table_name='reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_matches_bank_transaction_id'), table_name='reconciliation_matches')
    op.drop_table('reconciliation_matches')
    op.drop_index(op.f('ix_reconciliation_exceptions_tenant_id'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_status'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_severity'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_reconciliation_run_id'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_ledger_record_id'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_exception_type'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_exception_fingerprint'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_exception_code'), table_name='reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_exceptions_bank_transaction_id'), table_name='reconciliation_exceptions')
    op.drop_table('reconciliation_exceptions')
    op.drop_index(op.f('ix_reconciliation_decisions_tenant_id'), table_name='reconciliation_decisions')
    op.drop_index(op.f('ix_reconciliation_decisions_reconciliation_run_id'), table_name='reconciliation_decisions')
    op.drop_index(op.f('ix_reconciliation_decisions_match_group_id'), table_name='reconciliation_decisions')
    op.drop_index(op.f('ix_reconciliation_decisions_decision'), table_name='reconciliation_decisions')
    op.drop_index(op.f('ix_reconciliation_decisions_actor_user_id'), table_name='reconciliation_decisions')
    op.drop_table('reconciliation_decisions')
    op.drop_index(op.f('ix_reconciliation_allocations_tenant_id'), table_name='reconciliation_allocations')
    op.drop_index(op.f('ix_reconciliation_allocations_reconciliation_run_id'), table_name='reconciliation_allocations')
    op.drop_index(op.f('ix_reconciliation_allocations_match_group_id'), table_name='reconciliation_allocations')
    op.drop_index(op.f('ix_reconciliation_allocations_ledger_record_id'), table_name='reconciliation_allocations')
    op.drop_index(op.f('ix_reconciliation_allocations_bank_transaction_id'), table_name='reconciliation_allocations')
    op.drop_table('reconciliation_allocations')
    op.drop_index(op.f('ix_reconciliation_reports_tenant_id'), table_name='reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_reports_report_type'), table_name='reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_reports_reconciliation_run_id'), table_name='reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_reports_checksum'), table_name='reconciliation_reports')
    op.drop_table('reconciliation_reports')
    op.drop_index(op.f('ix_reconciliation_match_groups_tenant_id'), table_name='reconciliation_match_groups')
    op.drop_index(op.f('ix_reconciliation_match_groups_status'), table_name='reconciliation_match_groups')
    op.drop_index(op.f('ix_reconciliation_match_groups_reconciliation_run_id'), table_name='reconciliation_match_groups')
    op.drop_index(op.f('ix_reconciliation_match_groups_group_type'), table_name='reconciliation_match_groups')
    op.drop_index(op.f('ix_reconciliation_match_groups_group_fingerprint'), table_name='reconciliation_match_groups')
    op.drop_index(op.f('ix_reconciliation_match_groups_confidence'), table_name='reconciliation_match_groups')
    op.drop_index(op.f('ix_reconciliation_match_groups_auto_accepted'), table_name='reconciliation_match_groups')
    op.drop_table('reconciliation_match_groups')
    op.drop_index(op.f('ix_reconciliation_control_totals_tenant_id'), table_name='reconciliation_control_totals')
    op.drop_index(op.f('ix_reconciliation_control_totals_status'), table_name='reconciliation_control_totals')
    op.drop_index(op.f('ix_reconciliation_control_totals_reconciliation_run_id'), table_name='reconciliation_control_totals')
    op.drop_index(op.f('ix_reconciliation_control_totals_control_name'), table_name='reconciliation_control_totals')
    op.drop_table('reconciliation_control_totals')
    op.drop_index(op.f('ix_reconciliation_candidates_total_confidence'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_tenant_id'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_reconciliation_run_id'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_reconciliation_rule_id'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_match_group_key'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_ledger_record_id'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_candidate_type'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_candidate_status'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_candidate_fingerprint'), table_name='reconciliation_candidates')
    op.drop_index(op.f('ix_reconciliation_candidates_bank_transaction_id'), table_name='reconciliation_candidates')
    op.drop_table('reconciliation_candidates')
    op.drop_index(op.f('ix_bank_ledger_reconciliation_runs_validation_run_id'), table_name='bank_ledger_reconciliation_runs')
    op.drop_index(op.f('ix_bank_ledger_reconciliation_runs_tenant_id'), table_name='bank_ledger_reconciliation_runs')
    op.drop_index(op.f('ix_bank_ledger_reconciliation_runs_status'), table_name='bank_ledger_reconciliation_runs')
    op.drop_index(op.f('ix_bank_ledger_reconciliation_runs_ruleset_fingerprint'), table_name='bank_ledger_reconciliation_runs')
    op.drop_index(op.f('ix_bank_ledger_reconciliation_runs_reconciliation_version'), table_name='bank_ledger_reconciliation_runs')
    op.drop_index(op.f('ix_bank_ledger_reconciliation_runs_input_fingerprint'), table_name='bank_ledger_reconciliation_runs')
    op.drop_index(op.f('ix_bank_ledger_reconciliation_runs_date_to'), table_name='bank_ledger_reconciliation_runs')
    op.drop_index(op.f('ix_bank_ledger_reconciliation_runs_date_from'), table_name='bank_ledger_reconciliation_runs')
    op.drop_index(op.f('ix_bank_ledger_reconciliation_runs_bank_account_id'), table_name='bank_ledger_reconciliation_runs')
    op.drop_table('bank_ledger_reconciliation_runs')
    op.drop_index(op.f('ix_reconciliation_rules_tenant_id'), table_name='reconciliation_rules')
    op.drop_index(op.f('ix_reconciliation_rules_rule_type'), table_name='reconciliation_rules')
    op.drop_index(op.f('ix_reconciliation_rules_is_active'), table_name='reconciliation_rules')
    op.drop_index(op.f('ix_reconciliation_rules_code'), table_name='reconciliation_rules')
    op.drop_table('reconciliation_rules')
    # ### end Alembic commands ###
